basePath: /api/v1
definitions:
  model.Project:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  model.ProjectsPaged:
    properties:
      items:
        items:
          $ref: '#/definitions/model.Project'
        type: array
      page_index:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
    type: object
  model.Task:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      project_id:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  model.Tasks:
    properties:
      items:
        items:
          $ref: '#/definitions/model.Task'
        type: array
    type: object
  model.Tokens:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  model.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      middle_name:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  model.UsersPaged:
    properties:
      items:
        items:
          $ref: '#/definitions/model.User'
        type: array
      page_index:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: PMS - project management system. It is course work of student team
    for 5 course in MEPhI.
  termsOfService: http://swagger.io/terms/
  title: PMS API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Tokens'
      summary: Login
      tags:
      - Auth
  /logout:
    post:
      consumes:
      - application/json
      description: Logout
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Logout
      tags:
      - Auth
  /projects:
    get:
      consumes:
      - application/json
      description: Get projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProjectsPaged'
      summary: Get projects
      tags:
      - Project
    post:
      consumes:
      - application/json
      description: Create project
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Project'
      summary: Create project
      tags:
      - Project
  /projects/{id}:
    delete:
      consumes:
      - application/json
      description: Delete project
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Delete project
      tags:
      - Project
    get:
      consumes:
      - application/json
      description: Get project by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Project'
      summary: Get project by ID
      tags:
      - Project
    put:
      consumes:
      - application/json
      description: Update project
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Project'
      summary: Update project
      tags:
      - Project
  /projects/{id}/members:
    get:
      consumes:
      - application/json
      description: Get project members
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UsersPaged'
      summary: Get project members
      tags:
      - Project
  /projects/{id}/members/{user_id}:
    delete:
      consumes:
      - application/json
      description: Delete project member
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Delete project member
      tags:
      - Project
  /projects/{id}/tasks:
    get:
      consumes:
      - application/json
      description: Get project tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Tasks'
      summary: Get project tasks
      tags:
      - Project
  /projects/{project_id}/archive:
    put:
      description: Archive the project by id
      parameters:
      - description: Project id
        in: path
        name: project_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProjectsPaged'
      summary: Archive the project by id
      tags:
      - Project
  /projects/{project_id}/members/{user_id}:
    post:
      consumes:
      - application/json
      description: Add project member
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Add project member
      tags:
      - Project
  /projects/{project_id}/unarchive:
    put:
      description: Unarchive the project by id
      parameters:
      - description: Project id
        in: path
        name: project_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProjectsPaged'
      summary: Unarchive the project by id
      tags:
      - Project
  /projects/archived:
    get:
      description: Get archived projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProjectsPaged'
      summary: Get archived projects
      tags:
      - Project
  /refresh:
    post:
      consumes:
      - application/json
      description: Refresh
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Tokens'
      summary: Refresh
      tags:
      - Auth
  /task:
    post:
      consumes:
      - application/json
      description: Create task
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Task'
      summary: Create task
      tags:
      - Task
  /task/{id}:
    delete:
      consumes:
      - application/json
      description: Delete task
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete task
      tags:
      - Task
    get:
      consumes:
      - application/json
      description: Get task by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
      summary: Get task by ID
      tags:
      - Task
    put:
      consumes:
      - application/json
      description: Update task
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
      summary: Update task
      tags:
      - Task
  /users:
    get:
      consumes:
      - application/json
      description: Get users
      parameters:
      - description: Page index
        in: query
        name: pageIndex
        type: integer
      - description: Page size
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UsersPaged'
      summary: Get users
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create user
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
      summary: Create user
      tags:
      - User
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete User
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Delete user
      tags:
      - User
    get:
      consumes:
      - application/json
      description: Get user by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Get user by ID
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
      summary: Update user
      tags:
      - User
swagger: "2.0"
